//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAdmissionPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Programare_examen
    {
        public Nullable<decimal> ID_Candidat { get; set; }
        public Nullable<decimal> ID_Sala { get; set; }
        public Nullable<decimal> ID_Proba { get; set; }
        public Nullable<System.DateTime> Data_ora { get; set; }
        public int ID { get; set; }
    
        public virtual Candidati Candidati { get; set; }
        public virtual Probe Probe { get; set; }
        public virtual Sali_admitere Sali_admitere { get; set; }
    }
}
