//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAdmissionPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sali_admitere
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sali_admitere()
        {
            this.Programare_examen = new HashSet<Programare_examen>();
        }
    
        public decimal ID_Sala { get; set; }
        public string Nume_Sala { get; set; }
        public string Pavilion { get; set; }
        public Nullable<decimal> Etaj { get; set; }
        public Nullable<decimal> Capacitate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Programare_examen> Programare_examen { get; set; }
    }
}
