//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezultate_probe
    {
        public Nullable<decimal> ID_Candidat { get; set; }
        public Nullable<decimal> ID_Proba { get; set; }
        public Nullable<decimal> Nota { get; set; }
        public int ID { get; set; }
    
        public virtual Candidati Candidati { get; set; }
        public virtual Probe Probe { get; set; }
    }
}
